/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp03grupo9;

/**
 *
 * @author PUESTO-A1
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpEscritorio = new javax.swing.JDesktopPane();
        mnbOpciones = new javax.swing.JMenuBar();
        mnuAgenda = new javax.swing.JMenu();
        mniListar = new javax.swing.JMenuItem();
        mniCrear = new javax.swing.JMenuItem();
        mniBuscar = new javax.swing.JMenuItem();
        mniEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        dpEscritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        dpEscritorioLayout.setVerticalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        mnuAgenda.setText("Agenda");

        mniListar.setText("Listar");
        mniListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListarActionPerformed(evt);
            }
        });
        mnuAgenda.add(mniListar);

        mniCrear.setText("Nuevo");
        mniCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCrearActionPerformed(evt);
            }
        });
        mnuAgenda.add(mniCrear);

        mniBuscar.setText("Buscar");
        mniBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBuscarActionPerformed(evt);
            }
        });
        mnuAgenda.add(mniBuscar);

        mniEliminar.setText("Eliminar");
        mniEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEliminarActionPerformed(evt);
            }
        });
        mnuAgenda.add(mniEliminar);

        mnbOpciones.add(mnuAgenda);

        setJMenuBar(mnbOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBuscarActionPerformed
        dpEscritorio.removeAll();
        dpEscritorio.repaint();
        friBuscarCliente formBuscarCliente = new friBuscarCliente();
        formBuscarCliente.setVisible(true);
        dpEscritorio.add(formBuscarCliente);
        dpEscritorio.moveToFront(formBuscarCliente);
    }//GEN-LAST:event_mniBuscarActionPerformed

    private void mniCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCrearActionPerformed
        dpEscritorio.removeAll();
        dpEscritorio.repaint();
        friCrearCliente formCrearCliente = new friCrearCliente();
        formCrearCliente.setVisible(true);
        dpEscritorio.add(formCrearCliente);
        dpEscritorio.moveToFront(formCrearCliente);
    }//GEN-LAST:event_mniCrearActionPerformed

    private void mniEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEliminarActionPerformed
        dpEscritorio.removeAll();
        dpEscritorio.repaint();
        friEliminarCliente formEliminarCliente = new friEliminarCliente();
        formEliminarCliente.setVisible(true);
        dpEscritorio.add(formEliminarCliente);
        dpEscritorio.moveToFront(formEliminarCliente);
    }//GEN-LAST:event_mniEliminarActionPerformed

    private void mniListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListarActionPerformed
        dpEscritorio.removeAll();
        dpEscritorio.repaint();
        friListarClientes formListarClientes = new friListarClientes();
        formListarClientes.setVisible(true);
        dpEscritorio.add(formListarClientes);
        dpEscritorio.moveToFront(formListarClientes);
    }//GEN-LAST:event_mniListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpEscritorio;
    private javax.swing.JMenuBar mnbOpciones;
    private javax.swing.JMenuItem mniBuscar;
    private javax.swing.JMenuItem mniCrear;
    private javax.swing.JMenuItem mniEliminar;
    private javax.swing.JMenuItem mniListar;
    private javax.swing.JMenu mnuAgenda;
    // End of variables declaration//GEN-END:variables
}
